### PR TITLE
Port changes from development branch to master

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #28

@emiliom I tried to port `master` to `development` in #30 but would be a nightmare. Rebasing 30 commits on top of master is not a task for a human.

The other way around is also messy, so squashed @sreeder 30 commits from development into 1 and rebased `master` against that. If I got it right this PR should have all of @sreeder changes and all of the latest PRs to master but the code style changes and py3k fixes (I can re-do that later).

The reason the later is not there is b/c it would be too hard to tell apart new code from `development` or style changes from my PR.

### CODE REVIEW

**Comment by ocefpaf** [comment]
The CI failures seems to be due to API changes in the code that were not ported to the tests.

**Comment by emiliom** [comment]
cc @steveskrip

**Comment by emiliom** [comment]
@sreeder have you had a chance to review this PR?

**Comment by emiliom** [comment]
Ok, this **really needs to move forward** ASAP. I'm going to use the sledge hammer approach and blissfully merge this PR, counting on the good testing and assessment work y'all have already done. Then hopefully @sreeder and @steveskrip can do some final quick testing (today?) from master, we call it good, @sreeder creates a tagged release (or I can do that if it helps), and @ocefpaf goes off and updates the conda package right after.

**Pull request merged**
