### PR TITLE
Merge "Development" into "Master" branch

### PR DESCRIPTION
**Pull request by aufdenkampe**
This PR begins the process.
Waiting for @steveskrip to confirm that develop works.
Then we'll need to manually resolve merge conflicts, perhaps with help from @ocefpaf .

### CODE REVIEW

**Comment by emiliom** [comment]
Thanks for getting this started, @aufdenkampe.

@ocefpaf, your help will be most appreciated, specially after @steveskrip has had a chance to do some testing. Beware that this merge will be tricky (it's 29 files -- yikes). For some diffs, the master version should be kept (likely those that you touched in your "recent" PR's); but for ones that involve meaningful feature enhancements, naturally the dev branch version is it.

**Comment by ocefpaf** [comment]
Well, only 16 files in conflict :smile:

As soon as @steveskrip reports back with his testing I'll start.

@steveskrip if you find anything in your tests that could be added as unittests or integration tests please let us add it to the CI configuration.

**Comment by aufdenkampe** [comment]
@steveskrip, this is where you can find some possible test files:
* https://github.com/ODM2/YODA-File/blob/master/examples/time_series/v0.3.3/YODA_v0.3.3_TS_climate(wHeaders).xlsm
  * If you look at the history for this file, it was committed and edited during the same time as the "development" branch.
* https://github.com/ODM2/YODA-Tools/blob/master/Examples/test_ts.yaml

**Comment by emiliom** [comment]
And here's the repo of tutorial materials for the BiGCZ workshop, that I talked about at the call today:
https://github.com/BiG-CZ/wshp2017_tutorial_content
The "Example2" notebook is the one that flexes yodatools. Remember to remove `yodatools` from the conda environment file, and add `jupyter`

**Comment by emiliom** [comment]
@ocefpaf, Based on recent exchanges with you on PR #31 and elsewhere, it sounds like you're recommending that we withdraw this "bulk" PR and focus instead on more granular PR's such as #31, right?

**Comment by ocefpaf** [comment]
> @ocefpaf, Based on recent exchanges with you on PR #31 and elsewhere, it sounds like you're recommending that we withdraw this "bulk" PR and focus instead on more granular PR's such as #31, right?

Exactly. The relevant code changes from this branch are in #31

**Comment by emiliom** [comment]
Closing. See PR #31 instead. But note that some useful links to YODA examples are found in the discussions here.

**Pull request closed without merging**
