### PR TITLE
Fix code compliance, clarity, and lints.

### PR DESCRIPTION
**Pull request by ocefpaf**
This is a massive PR that I've been preparing for a while.
I thought about sending smaller pieces but sometimes it is better to bite the bullet and avoid re-bases.

It should not change the functionality, but this needs a careful review and testing before we merge.

Further Python 3 compliance should be easier once this one is in `master `.

### CODE REVIEW

**Comment by emiliom** [comment]
@horsburgh, with Stephanie on maternity leave, is there someone else in your team who can follow up with @ocefpaf on YODA-Tools work, for this PR and subsequent stuff? Or should we set this aside for a while?

**Comment by horsburgh** [comment]
@emiliom - I may be able to put Kenny on this soon, but he's busy at the moment with a couple of other things. We may have to pause for a bit until I can free him up.

**Comment by emiliom** [comment]
Thanks, @horsburgh. No worries. We (well, mostly @ocefpaf) will be standing by.

**Comment by emiliom** [comment]
@steveskrip, I'm pinging you here to get you explicitly in the loop of this PR (as well as PR's #24 and #26), and also as a reminder that we're all counting on you to move YODA-Tools to new heights. No pressure :smiley_cat:

I've already let @ocefpaf know that you'll follow up "soon" one way or another.

Thanks!
cc @aufdenkampe

**Comment by ocefpaf** [comment]
@steveskrip let me know if you have any questions. If you find it useful we can have a call to walk through the PRs.

**Comment by steveskrip** [comment]
@ocefpaf I'll take you up on that - I'll be in touch today or tomorrow.

**Pull request merged**
